version: '2'
services:
    mongodb:
        image: mongo
        ports:
            - "27017:27017"
    mongodb-seed:
        build: ./data
        links:
            - mongodb
    jupyter:
      build: .
      ports:
          - "8888:8888"
      links:
          - mongodb
